pre_install: |
  paru -Sy
dependencies:
- dot:base
- dot:gpu-amd-intel
- dot:greetd-tuigreet
- dot:wm-hyprland
- dot:kelgors-terminal
- dot:kelgors-desktop
- flatpak:md.obsidian.Obsidian
- flatpak:net.lutris.Lutris
- flatpak:com.github.IsmaelMartinez.teams_for_linux
- flatpak:org.filezillaproject.Filezilla
- flatpak:org.inkscape.Inkscape
- flatpak:org.musicbrainz.Picard
- flatpak:org.onlyoffice.desktopeditors
- dot:flatpak
- rust
- rust2
- rust3
- rust4
- rust5
